bobuhiro11/gokvm

kvm/kvm.go, kvm/kvm_test.go
=> kvm: add apis

Makefile, bootproto/bootproto.go, kvm/kvm.go, kvm/kvm_test.go, main.go
=> linux: support booting on kvm

Makefile, bootproto/bootproto_test.go, kvm/kvm.go, kvm/kvm_test.go, main.go
=> test: add unit tests

kvm/kvm.go, kvm/kvm_test.go, serial/serial.go, serial/serial_test.go
=> test: add missing test. mainly for serial

go.mod, go.sum, kvm/kvm.go, main.go, term/term.go
=> term: fix own implementation

flag/flag.go, flag/flag_test.go, main.go
=> flag: add arguments for kernel & initrd path

.goreleaser.yml, .travis.yml
=> ci: add goreleaser

.gitignore, .travis.yml, go.mod
=> ci: update go version in go.mod & install goveralls outside go module

flag/flag.go, flag/flag_test.go, machine/machine.go, machine/machine_test.go, main.go
=> cli: add kernel command-line parameters

term/term.go
=> term: use predefined flags for raw mode

kvm/kvm.go, machine/machine.go
=> machine: handle return code EINTR for ioctl KVM_RUN

.travis.yml, Makefile
=> ci: add --retry flag to curl

machine/machine.go
=> machine: fix inability to boot in Ubuntu 20.04 on wsl2

Makefile, machine/machine.go
=> ci: add `make run-system-kernel` command

bootparam/bootparam.go, machine/machine.go
=> bootparam: fix the logic of protocol version checking

README.md, bootparam/bootparam_test.go, flag/flag_test.go, go.mod, kvm/kvm_test.go, machine/machine.go, machine/machine_test.go, main.go, serial/serial_test.go
=> rename nmi to bobuhiro11

machine/machine.go
=> fix typos & code style

Makefile, ebda/ebda.go, flag/flag.go
=> flag, ebda: refactoring code

machine/machine.go
using standard `copy` should be faster than for loop
=> improve memory copy

Makefile
=> add lspci in pciutils to use completion by pci.ids

.travis.yml, Makefile
=> add ethtool

Makefile
=> fix Makefile to make linux rebuildable

machine/machine.go, pci/bridge.go, pci/pci.go, virtio/net.go
=> add interface for PCI device

.travis.yml
=> prevent tests from being rerun by goveralls

machine/machine.go, virtio/net.go, virtio/net_test.go
=> virtio: capture packets sent from guest on host's tap interface

Makefile
=> add ethtool & pciutils to "make clean"

kvm/kvm.go, term/term.go
=> kvm,term: fix error handling for syscall

.gitignore, .travis.yml, Makefile, go.mod
=> goinitrd: refactoring

machine/machine.go, main.go
We might make 0xcf9 writes more capable in the future,
but for now this is a reasonable first step.
0xCF9 port can get three values for three types of reset:
Writing 4 to 0xCF9:(INIT) Will INIT the CPU. Meaning it will jump to the
initial location of booting but it will keep many CPU elements
untouched. Most internal tables, chaches etc will remain unchanged by
the Init call (but may change during it).
Writing 6 to 0xCF9:(RESET) Will RESET the CPU with all internal tables
caches etc cleared to initial state.
Writing 0xE to 0xCF9:(RESTART) Will power cycle the mother board with
everything that comes with it.
=> Exit on writes to 0xcf9

.travis.yml, Makefile, kvm/kvm_test.go, virtio/blk.go
=> ci: support multi go version in travis-ci

.travis.yml, machine/machine_test.go
=> add Go 1.19.x in .travis.yaml

flag/flag.go, flag/flag_test.go, main.go
Turning on all tracing leads to a giant dump and slows down the kernel enough that many timing checks fail (e.g. lapic calibration).
-T now defines an interval or count of how many instructions to skip between printing.
E.g.,
gokvm -T 1048576
or
gokvm -T 1M
will print every million'th instruction.
This is useful to see where the kernel is, and makes booting pretty fast.
To get closer samples, you can
govkm -T 1000
The default value of -T, 0, means no tracing at all.
Signed-off-by: Ronald Minnich <rminnich@gmail.com>
=> Tracing: support printing fewer tracepoints

.travis.yml, go.mod, go.sum
=> run "go mod tidy"

.bashrc, Makefile, flag/flag.go, machine/machine.go, machine/machine_test.go
=> machine: Support vmlinux and bzImage for booting kernel test

README.md
Add https://github.com/torvalds/linux/blob/master/include/uapi/linux/kvm.h as reference
Signed-off-by: Christopher Meis <christopher.meis@9elements.com>
=> Add reference to kvm.h 

main.go, probe/capabilities.go
"tools" has no particular meaning, so I move the files into an easy-to-understand package called "probe".
=> probe: Move files from tools package into probe.

cpuid/cpuid.go, cpuid/cpuid.s, cpuid/cpuid_test.go
Add package CPUID for handling requests of CPUID of the host system and providing a mechanism to patch vCPU CPUIDs
=> Add package CPUID 

machine/machine.go
Close https://github.com/bobuhiro11/gokvm/issues/56
=> Unset X86_FEATURE_FSRM to avoid unexpected KVM Exit.
